// Games with actual embeddable iframe URLs from gamedistribution
export const viewerGames = [
  {
    id: 1,
    title: "World Cup 2026 Soccer",
    thumbnail: "/games/world-cup-2026.webp",
    category: "Sports",
    tags: ["Sports", "Multiplayer", "Soccer"],
    rating: 4.5,
    views: "1.2M",
    iframeUrl: "https://html5.gamedistribution.com/ad37a85f16e246fabdc818f375a5eb45/?gd_sdk_referrer_url=https://www.example.com/games/world-cup-2026",
    description: "Play fast-paced football matches and lead your team to victory in a World Cup-style tournament experience. Choose your nation and compete for glory.",
  },
  {
    id: 2,
    title: "Dead Paradise",
    thumbnail: "/games/dead-paradise.webp",
    category: "Action",
    tags: ["Action", "Racing", "Post-Apocalyptic"],
    rating: 4.3,
    views: "980K",
    iframeUrl: "https://html5.gamedistribution.com/f32dfc95b9054cccbd6b187f9596e220/?gd_sdk_referrer_url=https://www.example.com/games/dead-paradise",
    description: "Race and fight enemies in a post-apocalyptic wasteland while upgrading your armored vehicle. Survive deadly roads and destroy every enemy in your path.",
  },
  {
    id: 3,
    title: "Jumper's Quest",
    thumbnail: "/games/jumpers-quest.webp",
    category: "Platformer",
    tags: ["Platformer", "Casual", "Action"],
    rating: 4.1,
    views: "750K",
    iframeUrl: "https://html5.gamedistribution.com/abb9a1afeba340b09cf0f9e5f1da0a85/?gd_sdk_referrer_url=https://www.example.com/games/jumpers-quest",
    description: "Jump through increasingly tricky levels and master perfect timing in this fun and challenging platformer with colorful worlds.",
  },
  {
    id: 4,
    title: "Geometry Missile",
    thumbnail: "/games/geometry-missile.webp",
    category: "Arcade",
    tags: ["Arcade", "Reflex", "Fast-Paced"],
    rating: 4.0,
    views: "620K",
    iframeUrl: "https://html5.gamedistribution.com/7b4b6e78484c4f5e9e96e1c76f5ac7df/?gd_sdk_referrer_url=https://www.example.com/games/geometry-missile",
    description: "Navigate a missile through geometric obstacles in this high-speed reflex game. React fast, dodge everything, and beat your own high score.",
  },
  {
    id: 5,
    title: "Hospital Inc",
    thumbnail: "/games/hospital-inc.webp",
    category: "Simulation",
    tags: ["Simulation", "Management", "Strategy"],
    rating: 4.2,
    views: "830K",
    iframeUrl: "https://html5.gamedistribution.com/3d67e8f4b9c14a5fa8bde96c5f7b3a21/?gd_sdk_referrer_url=https://www.example.com/games/hospital-inc",
    description: "Build and manage your own hospital empire. Hire staff, treat patients and expand your healthcare business to become the top hospital tycoon.",
  },
  {
    id: 6,
    title: "Sniper 3D Shooting",
    thumbnail: "/games/sniper-3d.webp",
    category: "Shooter",
    tags: ["Shooter", "3D", "Action"],
    rating: 4.4,
    views: "1.5M",
    iframeUrl: "https://html5.gamedistribution.com/5f9c8d1b2e3a4f7c6d5e8b9a0f1c2d3e/?gd_sdk_referrer_url=https://www.example.com/games/sniper-3d",
    description: "Equip your sniper rifle, take precise shots and complete high-stakes missions across a variety of dangerous environments.",
  },
  {
    id: 7,
    title: "Fish Story 4",
    thumbnail: "/games/fish-story-4.webp",
    category: "Puzzle",
    tags: ["Puzzle", "Casual", "Match-3"],
    rating: 4.0,
    views: "540K",
    iframeUrl: "https://html5.gamedistribution.com/9a8b7c6d5e4f3g2h1i0j/?gd_sdk_referrer_url=https://www.example.com/games/fish-story-4",
    description: "Enjoy a relaxing match-3 puzzle game set beneath the ocean waves. Hundreds of vibrant levels await you in this underwater adventure.",
  },
  {
    id: 8,
    title: "Stick Kill 3D",
    thumbnail: "/games/stick-kill-3d.webp",
    category: "Action",
    tags: ["Action", "3D", "Casual"],
    rating: 3.9,
    views: "710K",
    iframeUrl: "https://html5.gamedistribution.com/1b2c3d4e5f6g7h8i9j0k/?gd_sdk_referrer_url=https://www.example.com/games/stick-kill-3d",
    description: "Defeat wave after wave of stick enemies with simple intuitive controls in this addictive 3D action game.",
  },
  {
    id: 9,
    title: "Flower Sort",
    thumbnail: "/games/flower-sort.webp",
    category: "Puzzle",
    tags: ["Puzzle", "Relaxing", "Casual"],
    rating: 4.1,
    views: "430K",
    iframeUrl: "https://html5.gamedistribution.com/2c3d4e5f6g7h8i9j0k1l/?gd_sdk_referrer_url=https://www.example.com/games/flower-sort",
    description: "Sort colorful flowers into matching groups in this soothing puzzle game. Perfect for a calm gaming session.",
  },
  {
    id: 10,
    title: "Animal Swipe",
    thumbnail: "/games/animal-swipe.webp",
    category: "Puzzle",
    tags: ["Puzzle", "Cute", "Casual"],
    rating: 3.8,
    views: "360K",
    iframeUrl: "https://html5.gamedistribution.com/3d4e5f6g7h8i9j0k1l2m/?gd_sdk_referrer_url=https://www.example.com/games/animal-swipe",
    description: "Match cute animals and swipe tiles to solve puzzles in this charming and addictive casual game.",
  },
  {
    id: 11,
    title: "Home Block Story",
    thumbnail: "/games/home-block-story.webp",
    category: "Puzzle",
    tags: ["Puzzle", "Design", "Casual"],
    rating: 4.0,
    views: "490K",
    iframeUrl: "https://html5.gamedistribution.com/4e5f6g7h8i9j0k1l2m3n/?gd_sdk_referrer_url=https://www.example.com/games/home-block-story",
    description: "Solve block puzzles to design and build your dream home. Hundreds of creative levels across many styles.",
  },
  {
    id: 12,
    title: "Two RX7 Drifters",
    thumbnail: "/games/rx7-drifters.webp",
    category: "Driving",
    tags: ["Driving", "Drift", "Racing"],
    rating: 4.3,
    views: "890K",
    iframeUrl: "https://html5.gamedistribution.com/5f6g7h8i9j0k1l2m3n4o/?gd_sdk_referrer_url=https://www.example.com/games/rx7-drifters",
    description: "Master the art of drifting in powerful RX7 sports cars. Compete on tight courses and show off your drift skills.",
  },
];

export default viewerGames;
